# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: geek.reisener.asia
email: stefan@reisener.asia

#write html inside the double quotes to display in jumbotron
description: "<h2>Welcome to my little tech blog!</h2>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geek.reisener.asia/" # the base hostname & protocol for your site
twitter_username: 636_stefan
github_username:  636stefan

# Build settings
markdown: kramdown
